version: "2"

run:
  timeout: 2m

linters:
  enable:
    - govet
    - gosec
    - errcheck
    - staticcheck

linters-settings:
  staticcheck:
    checks:
      - "all"
      - "-SA1019"

issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1019.*deprecated"